# Generated by Django 5.1.5 on 2025-01-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=255)),
                ('numero_contacto', models.CharField(blank=True, max_length=255, null=True)),
                ('rut', models.CharField(max_length=255)),
            ],
        ),
    ]
