# Generated by Django 5.1.5 on 2025-01-28 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clientes',
            table='clientes',
        ),
    ]
