# Generated by Django 5.1.5 on 2025-01-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_clientes_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='id_corredor',
            field=models.CharField(default='1', max_length=255),
        ),
    ]
