# Generated by Django 5.1.5 on 2025-02-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corredor',
            name='reset_token',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='corredor',
            name='token_expira',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='corredor',
            name='correo',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='corredor',
            name='rut',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
