# Generated by Django 5.1.5 on 2025-01-30 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_casa', models.CharField(blank=True, max_length=255, null=True)),
                ('comuna', models.CharField(max_length=255)),
                ('calle', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('numero_calle', models.IntegerField(blank=True, null=True)),
                ('numero_rol', models.IntegerField()),
                ('titulo', models.CharField(max_length=45)),
                ('nueva', models.BinaryField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('posee_casa', models.BinaryField(blank=True, null=True)),
                ('numero_lote', models.CharField(blank=True, max_length=45, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('video', models.CharField(blank=True, max_length=100, null=True)),
                ('id_propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedad.propietario')),
            ],
            options={
                'db_table': 'propiedad',
            },
        ),
    ]
