# Generated by Django 5.0.1 on 2025-06-24 22:11

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
        ('propietarios', '0002_rename_apellido_propietario_razon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcionOtros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_casa', models.CharField(blank=True, max_length=255, null=True)),
                ('comuna', models.CharField(max_length=255)),
                ('calle', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('numero_calle', models.IntegerField(blank=True, null=True)),
                ('numero_rol', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=100)),
                ('nueva', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('posee_casa', models.BooleanField(blank=True, null=True)),
                ('numero_lote', models.CharField(blank=True, max_length=45, null=True)),
                ('video', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video')),
                ('superficie_terreno', models.CharField(blank=True, max_length=255, null=True)),
                ('superficie_construida', models.CharField(blank=True, max_length=255, null=True)),
                ('anio_construccion', models.CharField(blank=True, max_length=255, null=True)),
                ('gastos_comunes', models.CharField(blank=True, max_length=255, null=True)),
                ('dormitorios', models.CharField(blank=True, max_length=255, null=True)),
                ('banios', models.CharField(blank=True, max_length=255, null=True)),
                ('estacionamiento', models.CharField(blank=True, max_length=255, null=True)),
                ('bodegas', models.CharField(blank=True, max_length=255, null=True)),
                ('pisos', models.CharField(blank=True, max_length=255, null=True)),
                ('oficinas', models.CharField(blank=True, max_length=255, null=True)),
                ('recintos', models.CharField(blank=True, max_length=255, null=True)),
                ('sector', models.CharField(blank=True, max_length=255, null=True)),
                ('factibilidad_agua', models.CharField(max_length=50)),
                ('factibilidad_electricidad', models.CharField(max_length=50)),
                ('factibilidad_alcantarillado', models.CharField(max_length=50)),
                ('factibilidad_gas', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('tipo_propiedad', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_propiedad', models.CharField(blank=True, max_length=255, null=True)),
                ('id_corredor_encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.corredor')),
                ('id_propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propietarios.propietario')),
                ('otros', models.ManyToManyField(blank=True, to='propiedad.opcionotros')),
            ],
            options={
                'db_table': 'propiedad',
            },
        ),
        migrations.CreateModel(
            name='ImagenPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen')),
                ('cloudinary_public_id', models.CharField(blank=True, max_length=255, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('es_portada', models.BooleanField(default=False)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='propiedad.propiedad')),
            ],
            options={
                'db_table': 'imagen_propiedad',
                'ordering': ['orden'],
            },
        ),
    ]
