# Generated by Django 5.1.5 on 2025-02-03 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0002_alter_propiedad_id_propietario_remove_propiedad_url_and_more'),
        ('propietarios', '0002_alter_propietario_numero_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='id_propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to='propietarios.propietario'),
        ),
    ]
