# Generated by Django 5.1.5 on 2025-02-19 13:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0005_propiedad_anio_construccion_propiedad_baños_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='fecha_creacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
