# Generated by Django 5.1.5 on 2025-02-19 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0008_propiedad_tipo_creacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propiedad',
            old_name='baños',
            new_name='banios',
        ),
    ]
