# Generated by Django 5.1.5 on 2025-03-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0014_propiedad_id_corredor_encargado'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='tipo_propiedad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
