# Generated by Django 5.1.5 on 2025-03-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0015_propiedad_tipo_propiedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='factibilidad_agua',
            field=models.CharField(choices=[('Venta', 'Venta'), ('Arriendo', 'Arriendo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='factibilidad_alcantarillado',
            field=models.CharField(choices=[('Venta', 'Venta'), ('Arriendo', 'Arriendo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='factibilidad_electricidad',
            field=models.CharField(choices=[('Venta', 'Venta'), ('Arriendo', 'Arriendo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='factibilidad_gas',
            field=models.CharField(choices=[('Venta', 'Venta'), ('Arriendo', 'Arriendo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='nueva',
            field=models.CharField(choices=[('Venta', 'Venta'), ('Arriendo', 'Arriendo')], max_length=50),
        ),
    ]
