# Generated by Django 5.1.5 on 2025-03-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0018_alter_propiedad_factibilidad_agua_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='codigo_propiedad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
