# Generated by Django 5.0.1 on 2025-06-24 19:29

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0019_propiedad_codigo_propiedad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenpropiedad',
            options={'ordering': ['orden']},
        ),
        migrations.AddField(
            model_name='imagenpropiedad',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='imagenpropiedad',
            name='es_portada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imagenpropiedad',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imagenpropiedad',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
    ]
