# Generated by Django 5.1.5 on 2025-03-04 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propiedad', '0014_propiedad_id_corredor_encargado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado_vale_vista', models.CharField(max_length=255)),
                ('valor_vale_vista', models.IntegerField()),
                ('id_propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedad.propiedad')),
            ],
        ),
    ]
