# Generated by Django 5.1.5 on 2025-03-04 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comision',
            table='comisiones_venta',
        ),
    ]
