# Generated by Django 5.1.5 on 2025-03-04 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0002_alter_comision_table'),
        ('documentos', '0003_rename_tipo_docu_documento_tipo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='comision',
            name='id_documento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documentos.documento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comision',
            name='estado_vale_vista',
            field=models.CharField(choices=[('Retenido', 'Retenido'), ('Aprobado', 'Aprobado')], default='Retenido', max_length=255),
        ),
    ]
