# Generated by Django 5.1.5 on 2025-03-04 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0003_comision_id_documento_and_more'),
        ('login', '0002_corredor_reset_token_corredor_token_expira_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comision',
            name='id_corredor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.corredor'),
            preserve_default=False,
        ),
    ]
