# Generated by Django 5.1.5 on 2025-03-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0004_comision_id_corredor'),
    ]

    operations = [
        migrations.AddField(
            model_name='comision',
            name='tipo_valor',
            field=models.CharField(choices=[('UF', 'UF'), ('CLP', 'CLP')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
