# Generated by Django 5.1.5 on 2025-03-06 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0006_remove_comision_tipo_valor_egresos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='egresos',
            old_name='valor_vale_vista',
            new_name='valor_egreso',
        ),
    ]
