# Generated by Django 5.0.1 on 2025-06-24 22:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='corredor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=10, unique=True)),
                ('correo', models.EmailField(max_length=255, unique=True)),
                ('numero_contacto', models.CharField(blank=True, max_length=255, null=True)),
                ('contrasenia', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateField(default=django.utils.timezone.now)),
                ('reset_token', models.UUIDField(blank=True, default=None, null=True)),
                ('token_expira', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'corredor',
            },
        ),
    ]
