# Generated by Django 5.0.1 on 2025-06-24 22:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacto_interesado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('numero_contacto', models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='El número de contacto debe tener 9 dígitos y comenzar con un número entre 2 y 9.', regex='^[2-9]\\d{8}$')])),
                ('mensaje', models.TextField()),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('corredor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corredores_2', to='login.corredor')),
                ('id_publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='operaciones.publicacion')),
            ],
            options={
                'db_table': 'contacto_interesado',
            },
        ),
        migrations.CreateModel(
            name='contacto_propietario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('numero_contacto', models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='El número de contacto debe tener 9 dígitos y comenzar con un número entre 2 y 9.', regex='^[2-9]\\d{8}$')])),
                ('mensaje', models.TextField()),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('corredor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corredores', to='login.corredor')),
            ],
            options={
                'db_table': 'contacto_propietario',
            },
        ),
    ]
