# Generated by Django 5.1.5 on 2025-02-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto_corredor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto_propietario',
            name='numero_contacto',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
