# Generated by Django 5.1.5 on 2025-02-21 19:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto_corredor', '0003_alter_contacto_propietario_numero_contacto'),
        ('login', '0002_corredor_reset_token_corredor_token_expira_and_more'),
        ('operaciones', '0009_alter_publicacion_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacto_interesado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('numero_contacto', models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='El número de contacto debe tener 9 dígitos y comenzar con un número entre 2 y 9.', regex='^[2-9]\\d{8}$')])),
                ('mensaje', models.TextField()),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('corredor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corredores_2', to='login.corredor')),
                ('id_publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='operaciones.publicacion')),
            ],
            options={
                'db_table': 'contacto_interesado',
            },
        ),
    ]
