# Generated by Django 5.1.5 on 2025-01-30 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0001_initial'),
        ('propietarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='id_propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propietarios.propietario'),
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='url',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='video',
        ),
        migrations.DeleteModel(
            name='Propietario',
        ),
    ]
