# Generated by Django 5.1.5 on 2025-02-14 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0003_alter_propiedad_id_propietario'),
        ('propietarios', '0003_rename_apellido_propietario_razon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='id_propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propietarios.propietario'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='nueva',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='posee_casa',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ImagenPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagen/')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='propiedad.propiedad')),
            ],
            options={
                'db_table': 'imagen_propiedad',
            },
        ),
    ]
