# Generated by Django 5.1.5 on 2025-02-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0004_propiedad_video_alter_propiedad_id_propietario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='anio_construccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='baños',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='bodegas',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='dormitorios',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='estacionamiento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='factibilidad_agua',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='factibilidad_alcantarillado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='factibilidad_electricidad',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='factibilidad_gas',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='gastos_comunes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='oficinas',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='otros',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='pisos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='recintos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='sector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='superficie_construida',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='superficie_terreno',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
