# Generated by Django 5.1.5 on 2025-02-19 13:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0006_propiedad_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='fecha_creacion',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
