# Generated by Django 5.1.5 on 2025-02-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0007_alter_propiedad_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='tipo_creacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
