# Generated by Django 5.1.5 on 2025-02-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0009_rename_baños_propiedad_banios'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcionOtros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='otros',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='otros',
            field=models.ManyToManyField(blank=True, to='propiedad.opcionotros'),
        ),
    ]
