# Generated by Django 5.1.5 on 2025-02-20 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0010_opcionotros_remove_propiedad_otros_propiedad_otros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='tipo_creacion',
        ),
    ]
