# Generated by Django 5.1.5 on 2025-02-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0011_remove_propiedad_tipo_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='numero_rol',
            field=models.CharField(max_length=255),
        ),
    ]
