# Generated by Django 5.1.5 on 2025-02-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0012_alter_propiedad_numero_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
