# Generated by Django 5.1.5 on 2025-02-24 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_corredor_reset_token_corredor_token_expira_and_more'),
        ('propiedad', '0013_alter_propiedad_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='id_corredor_encargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.corredor'),
        ),
    ]
