# Generated by Django 5.1.5 on 2025-02-21 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propiedad', '0013_alter_propiedad_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_docu', models.CharField(max_length=255)),
                ('pdf_documento', models.FileField(blank=True, null=True, upload_to='documentos/docu_venta/')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateField()),
                ('id_propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedad.propiedad')),
            ],
        ),
    ]
