# Generated by Django 5.1.5 on 2025-02-24 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_alter_documento_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='tipo_docu',
            new_name='tipo_documento',
        ),
    ]
