# Generated by Django 5.1.5 on 2025-02-12 21:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_corredor_reset_token_corredor_token_expira_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacto_propietario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('numero_contacto', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('corredor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corredores', to='login.corredor')),
            ],
            options={
                'db_table': 'contacto_propietario',
            },
        ),
    ]
