# Generated by Django 5.1.5 on 2025-02-14 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto_corredor', '0002_alter_contacto_propietario_numero_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto_propietario',
            name='numero_contacto',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='El número de contacto debe tener 9 dígitos y comenzar con un número entre 2 y 9.', regex='^[2-9]\\d{8}$')]),
        ),
    ]
