# Generated by Django 5.1.5 on 2025-02-07 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propietarios', '0002_alter_propietario_numero_contacto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propietario',
            old_name='apellido',
            new_name='razon',
        ),
        migrations.RenameField(
            model_name='propietario',
            old_name='nombre',
            new_name='representante',
        ),
    ]
