# Generated by Django 5.0.1 on 2025-06-24 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0001_initial'),
        ('login', '0001_initial'),
        ('propiedad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacionVenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('progreso', models.IntegerField(default=0)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_antecedentes', models.CharField(blank=True, choices=[('NO INICIADA', 'NO INICIADA'), ('OMITIDA', 'OMITIDA'), ('ANULADA', 'ANULADA'), ('REALIZADA', 'REALIZADA')], default='NO DATA', max_length=255, null=True)),
                ('estado_agendamiento', models.CharField(blank=True, choices=[('NO INICIADA', 'NO INICIADA'), ('AGENDADA', 'AGENDADA'), ('ANULADA', 'ANULADA'), ('REALIZADA', 'REALIZADA')], default='NO DATA', max_length=255, null=True)),
                ('estado_cierre_negocio', models.CharField(blank=True, choices=[('NO INICIADA', 'NO INICIADA'), ('PRESENTADA', 'PRESENTADA'), ('RECHAZADA', 'RECHAZADA'), ('ANULADA', 'ANULADA'), ('ACEPTADA', 'ACEPTADA')], default='NO DATA', max_length=255, null=True)),
                ('estado_promesa', models.CharField(blank=True, choices=[('NO INICIADA', 'NO INICIADA'), ('PRESENTADA', 'PRESENTADA'), ('RECHAZADA', 'RECHAZADA'), ('ANULADA', 'ANULADA'), ('ACEPTADA', 'ACEPTADA')], default='NO DATA', max_length=255, null=True)),
                ('estado_escritura', models.CharField(blank=True, choices=[('NO INICIADA', 'NO INICIADA'), ('PRESENTADA', 'PRESENTADA'), ('RECHAZADA', 'RECHAZADA'), ('ANULADA', 'ANULADA'), ('ACEPTADA', 'ACEPTADA')], default='NO DATA', max_length=255, null=True)),
                ('estado_inscripcion', models.CharField(blank=True, choices=[('NO INICIADA', 'NO INICIADA'), ('PRESENTADA', 'PRESENTADA'), ('RECHAZADA', 'RECHAZADA'), ('ANULADA', 'ANULADA'), ('ACEPTADA', 'ACEPTADA')], default='NO DATA', max_length=255, null=True)),
                ('estado_entrega', models.CharField(blank=True, choices=[('NO INICIADA', 'NO INICIADA'), ('CANCELADA', 'CANCELADA'), ('ANULADA', 'ANULADA'), ('ENTREGADA', 'ENTREGADA')], default='NO DATA', max_length=255, null=True)),
                ('fecha_creacion_operacion', models.DateTimeField(auto_now_add=True)),
                ('comision_operacion', models.IntegerField()),
                ('valor_operacion', models.IntegerField()),
                ('id_corredor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.corredor')),
                ('id_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.documento')),
                ('id_propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedad.propiedad')),
            ],
            options={
                'db_table': 'Operacion_Venta',
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('valor', models.IntegerField()),
                ('tipo_publicacion', models.CharField(choices=[('Venta', 'Venta'), ('Arriendo', 'Arriendo')], max_length=50)),
                ('tipo_valor', models.CharField(choices=[('CLP', 'CLP'), ('UF', 'UF')], max_length=50)),
                ('tipo_negocio', models.CharField(choices=[('Particular', 'Particular'), ('Inmobiliaria', 'Inmobiliaria')], max_length=50)),
                ('destacada', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateField()),
                ('comision_estimada', models.IntegerField()),
                ('id_corredor_encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.corredor')),
                ('id_propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedad.propiedad')),
            ],
            options={
                'db_table': 'publicacion',
            },
        ),
    ]
