# Generated by Django 5.1.5 on 2025-02-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='destacada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='tipo_negocio',
            field=models.CharField(choices=[('particular', 'Particular'), ('inmobiliaria', 'Inmobiliaria')], max_length=50),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='tipo_publicacion',
            field=models.CharField(choices=[('venta', 'Venta'), ('arriendo', 'Arriendo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='tipo_valor',
            field=models.CharField(choices=[('CLP', 'UF'), ('clp', 'uf')], max_length=50),
        ),
    ]
