# Generated by Django 5.1.5 on 2025-02-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0003_alter_publicacion_tipo_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='tipo_publicacion',
            field=models.CharField(choices=[('Venta', 'Venta'), ('Arriendo', 'Arriendo')], max_length=50),
        ),
    ]
