# Generated by Django 5.1.5 on 2025-02-21 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_corredor_reset_token_corredor_token_expira_and_more'),
        ('operaciones', '0005_alter_publicacion_tipo_negocio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='id_corredor_encargado',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.corredor'),
        ),
    ]
