# Generated by Django 5.0.1 on 2025-06-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0014_operacionventa_progreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacionventa',
            name='estado_agendamiento',
            field=models.CharField(blank=True, choices=[('NO INICIADA', 'NO INICIADA'), ('AGENDADA', 'AGENDADA'), ('ANULADA', 'ANULADA'), ('REALIZADA', 'REALIZADA')], default='NO DATA', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='operacionventa',
            name='estado_antecedentes',
            field=models.CharField(blank=True, choices=[('NO INICIADA', 'NO INICIADA'), ('OMITIDA', 'OMITIDA'), ('ANULADA', 'ANULADA'), ('REALIZADA', 'REALIZADA')], default='NO DATA', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='operacionventa',
            name='estado_entrega',
            field=models.CharField(blank=True, choices=[('NO INICIADA', 'NO INICIADA'), ('CANCELADA', 'CANCELADA'), ('ANULADA', 'ANULADA'), ('ENTREGADA', 'ENTREGADA')], default='NO DATA', max_length=255, null=True),
        ),
    ]
