# Generated by Django 5.1.5 on 2025-02-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propietarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='numero_contacto',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
