# Generated by Django 5.0.1 on 2025-06-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propietarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propietario',
            old_name='apellido',
            new_name='razon',
        ),
        migrations.RenameField(
            model_name='propietario',
            old_name='nombre',
            new_name='representante',
        ),
        migrations.AlterField(
            model_name='propietario',
            name='numero_contacto',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
