# Generated by Django 5.1.5 on 2025-02-17 17:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propiedad', '0005_propiedad_anio_construccion_propiedad_baños_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='publicacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('valor', models.IntegerField()),
                ('tipo_publicacion', models.CharField(max_length=255)),
                ('tipo_valor', models.CharField(max_length=255)),
                ('tipo_negocio', models.CharField(max_length=255)),
                ('destacada', models.BooleanField()),
                ('estado', models.BooleanField()),
                ('fecha_creacion', models.DateField(default=django.utils.timezone.now)),
                ('fecha_expiracion', models.DateField()),
                ('comision_estimada', models.IntegerField()),
                ('id_propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedad.propiedad')),
            ],
            options={
                'db_table': 'publicacion',
            },
        ),
    ]
