# Generated by Django 5.1.5 on 2025-02-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_alter_publicacion_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='tipo_valor',
            field=models.CharField(choices=[('CLP', 'CLP'), ('UF', 'UF')], max_length=50),
        ),
    ]
