# Generated by Django 5.1.5 on 2025-02-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0004_alter_publicacion_tipo_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='tipo_negocio',
            field=models.CharField(choices=[('Particular', 'Particular'), ('Inmobiliaria', 'Inmobiliaria')], max_length=50),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='tipo_publicacion',
            field=models.CharField(choices=[('venta', 'Venta'), ('arriendo', 'Arriendo')], max_length=50),
        ),
    ]
