# Generated by Django 5.1.5 on 2025-02-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0006_publicacion_id_corredor_encargado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='tipo_publicacion',
            field=models.CharField(choices=[('Venta', 'Venta'), ('Arriendo', 'Arriendo')], max_length=50),
        ),
    ]
