# Generated by Django 5.1.5 on 2025-02-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0008_alter_publicacion_id_corredor_encargado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
