# Generated by Django 5.1.5 on 2025-02-24 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_alter_documento_fecha'),
        ('operaciones', '0009_alter_publicacion_descripcion'),
        ('propiedad', '0013_alter_propiedad_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacionVenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_antecedentes', models.CharField(blank=True, choices=[('CANCELADA', 'CANCELADA'), ('REALIZADA', 'REALIZADA'), ('OMITIDA', 'OMITIDA')], default='NO DATA', max_length=255, null=True)),
                ('estado_agendamiento', models.CharField(blank=True, choices=[('CANCELADA', 'CANCELADA'), ('REALIZADA', 'REALIZADA'), ('AGENDADA', 'AGENDADA')], default='NO DATA', max_length=255, null=True)),
                ('estado_cierre_negocio', models.CharField(blank=True, choices=[('PRESENTADA', 'PRESENTADA'), ('ACEPTADA', 'ACEPTADA'), ('RECHAZADA', 'RECHAZADA')], default='NO DATA', max_length=255, null=True)),
                ('estado_promesa', models.CharField(blank=True, choices=[('CANCELADA', 'CANCELADA'), ('REALIZADA', 'REALIZADA'), ('OMITIDA', 'OMITIDA')], default='NO DATA', max_length=255, null=True)),
                ('estado_escritura', models.CharField(blank=True, choices=[('PRESENTADA', 'PRESENTADA'), ('ACEPTADA', 'ACEPTADA'), ('CANCELADA', 'CANCELADA')], default='NO DATA', max_length=255, null=True)),
                ('estado_inscripcion', models.CharField(blank=True, choices=[('EN PROCESO', 'EN PROCESO'), ('ACEPTADA', 'ACEPTADA'), ('CANCELADA', 'CANCELADA')], default='NO DATA', max_length=255, null=True)),
                ('estado_entrega', models.CharField(blank=True, choices=[('EN PROCESO', 'EN PROCESO'), ('ENTREGADA', 'ENTREGADA'), ('CANCELADA', 'CANCELADA')], default='NO DATA', max_length=255, null=True)),
                ('fecha_creacion_operacion', models.DateTimeField(auto_now_add=True)),
                ('comision_operacion', models.IntegerField()),
                ('valor_operacion', models.IntegerField()),
                ('id_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.documento')),
                ('id_propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedad.propiedad')),
            ],
        ),
    ]
