# Generated by Django 5.1.5 on 2025-02-24 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0010_operacionventa'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='operacionventa',
            table='Operacion_Venta',
        ),
    ]
