# Generated by Django 5.1.5 on 2025-02-24 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_corredor_reset_token_corredor_token_expira_and_more'),
        ('operaciones', '0011_alter_operacionventa_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacionventa',
            name='id_corredor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.corredor'),
        ),
        migrations.AlterField(
            model_name='operacionventa',
            name='estado_promesa',
            field=models.CharField(blank=True, choices=[('PRESENTADA', 'PRESENTADA'), ('ACEPTADA', 'ACEPTADA'), ('CANCELADA', 'CANCELADA')], default='NO DATA', max_length=255, null=True),
        ),
    ]
