# Generated by Django 5.1.5 on 2025-02-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0012_operacionventa_id_corredor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacionventa',
            name='estado_agendamiento',
            field=models.CharField(blank=True, choices=[('NO INICIADA', 'NO INICIADA'), ('AGENDADA', 'AGENDADA'), ('REALIZADA', 'REALIZADA'), ('ANULADA', 'ANULADA')], default='NO DATA', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='operacionventa',
            name='estado_antecedentes',
            field=models.CharField(blank=True, choices=[('NO INICIADA', 'NO INICIADA'), ('OMITIDA', 'OMITIDA'), ('REALIZADA', 'REALIZADA'), ('ANULADA', 'ANULADA')], default='NO DATA', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='operacionventa',
            name='estado_cierre_negocio',
            field=models.CharField(blank=True, choices=[('NO INICIADA', 'NO INICIADA'), ('PRESENTADA', 'PRESENTADA'), ('RECHAZADA', 'RECHAZADA'), ('ANULADA', 'ANULADA'), ('ACEPTADA', 'ACEPTADA')], default='NO DATA', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='operacionventa',
            name='estado_entrega',
            field=models.CharField(blank=True, choices=[('NO INICIADA', 'NO INICIADA'), ('ENTREGADA', 'ENTREGADA'), ('CANCELADA', 'CANCELADA'), ('ANULADA', 'ANULADA')], default='NO DATA', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='operacionventa',
            name='estado_escritura',
            field=models.CharField(blank=True, choices=[('NO INICIADA', 'NO INICIADA'), ('PRESENTADA', 'PRESENTADA'), ('RECHAZADA', 'RECHAZADA'), ('ANULADA', 'ANULADA'), ('ACEPTADA', 'ACEPTADA')], default='NO DATA', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='operacionventa',
            name='estado_inscripcion',
            field=models.CharField(blank=True, choices=[('NO INICIADA', 'NO INICIADA'), ('PRESENTADA', 'PRESENTADA'), ('RECHAZADA', 'RECHAZADA'), ('ANULADA', 'ANULADA'), ('ACEPTADA', 'ACEPTADA')], default='NO DATA', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='operacionventa',
            name='estado_promesa',
            field=models.CharField(blank=True, choices=[('NO INICIADA', 'NO INICIADA'), ('PRESENTADA', 'PRESENTADA'), ('RECHAZADA', 'RECHAZADA'), ('ANULADA', 'ANULADA'), ('ACEPTADA', 'ACEPTADA')], default='NO DATA', max_length=255, null=True),
        ),
    ]
