# Generated by Django 5.1.5 on 2025-03-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0013_alter_operacionventa_estado_agendamiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacionventa',
            name='progreso',
            field=models.IntegerField(default=0),
        ),
    ]
