# Generated by Django 5.0.1 on 2025-06-24 22:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0001_initial'),
        ('login', '0001_initial'),
        ('propiedad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado_vale_vista', models.CharField(choices=[('Retenido', 'Retenido'), ('Aprobado', 'Aprobado')], default='Retenido', max_length=255)),
                ('valor_vale_vista', models.IntegerField()),
                ('fecha_creacion', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('id_corredor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.corredor')),
                ('id_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.documento')),
                ('id_propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedad.propiedad')),
            ],
            options={
                'db_table': 'comisiones_venta',
            },
        ),
        migrations.CreateModel(
            name='Egresos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('valor_egreso', models.IntegerField()),
                ('fecha_creacion', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('id_corredor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.corredor')),
            ],
            options={
                'db_table': 'egreso_dinero',
            },
        ),
    ]
