# Generated by Django 5.1.5 on 2025-03-06 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0005_comision_tipo_valor'),
        ('login', '0002_corredor_reset_token_corredor_token_expira_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comision',
            name='tipo_valor',
        ),
        migrations.CreateModel(
            name='Egresos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('valor_vale_vista', models.IntegerField()),
                ('id_corredor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.corredor')),
            ],
        ),
    ]
