# Generated by Django 5.1.5 on 2025-03-06 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0007_rename_valor_vale_vista_egresos_valor_egreso'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='egresos',
            table='egreso_dinero',
        ),
    ]
