# Generated by Django 5.1.5 on 2025-03-06 16:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0008_alter_egresos_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='comision',
            name='fecha_creacion',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='egresos',
            name='fecha_creacion',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
